server:
  port: 8083

spring:
  rabbitmq:
    host: ${QUEUE_HOST:localhost}
    port: ${QUEUE_PORT:5672}
    username: ${QUEUE_USERNAME:guest}
    password: ${QUEUE_PASSWORD:guest}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB:safe_child_db}
    username: ${DB_USERNAME:aaron}
    password: ${DB_PASSWORD:aaron}
  jpa:
    show-sql: true
    hibernate:
      dll-auto: none
      show: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

notification:
  routing:
    key:
      sms: sms.routing
  queue:
    name:
      sms: sms.queue
  exchange:
    name: notification.exchange

pandora-sms:
  url: https://www.sms.thepandoranetworks.com/API/send_sms/?
  username: 0703958863
  password: M0b1c4s#
  sender: SafeChild
  message-type: info
  message-category: bulk

url:
  access:
    token: http://135.181.158.109:2022/oauth/token
  sms:
    payment: http://135.181.158.109:2022/


core:
  username: 120482
  password: admin
  client-id: client
  secret: client